Completely remove fmt package
This completely removes the fmt package, from both the compiled
library code and all tests.

It looks lik the importing function currently isn't strict enough,
but for now it's probably "good enough":

```
$ go test stl/stl_test/*go
--- FAIL: TestFrom_BinaryError (0.01s)
    stl_test.go:139: expecting error, got none
--- FAIL: TestFrom_ASCIIErrorLine (0.01s)
    stl_test.go:187: expecting error, got none
FAIL
FAIL    command-line-arguments  0.019s
FAIL
```