Snapshot of code causing an error when built with TinyGo
```
$ tinygo build -target wasm -o foo.wasm bundle.go
inlinable function call in a function with debug info must have a !dbg location
  call void @runtime.nilPanic(i8* undef, i8* null)
inlinable function call in a function with debug info must have a !dbg location
  %9 = call fastcc i1 @fmt.notSpace(i32 %7, i8* %2, i8* undef)
inlinable function call in a function with debug info must have a !dbg location
  %10 = call fastcc i1 @unicode.IsSpace(i32 %7, i8* %2, i8* undef)
inlinable function call in a function with debug info must have a !dbg location
  call void @runtime.nilPanic(i8* undef, i8* null)
inlinable function call in a function with debug info must have a !dbg location
  %12 = call fastcc i1 @fmt.notSpace(i32 %9, i8* %2, i8* undef)
inlinable function call in a function with debug info must have a !dbg location
  %13 = call fastcc i1 @unicode.IsSpace(i32 %9, i8* %2, i8* undef)
error: optimizations caused a verification failure
```